project_id = "pnwelorcrncqltqiyxwx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"
port = 54323
max_connections = 100
max_channels_per_client = 100
max_joins_per_second = 100
max_events_per_second = 100

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
max_frequency = "1h"

[auth.email.template.invite]
subject = "You have been invited"
content_path = "./supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm Your Signup"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset Your Password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your Magic Link"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirm Email Change"
content_path = "./supabase/templates/email_change.html"

[auth.sms]
enable_signup = true
enable_confirmations = false
max_frequency = "5m"
template = "Your code is {{ .Code }} ."

[storage]
enabled = true
file_size_limit = "50MiB"

[functions.create-mp-preference]
verify_jwt = false

[functions.generate-daily-report]
verify_jwt = false

[functions.generate-inactive-customer-tasks]
verify_jwt = false

[functions.generate-pix]
verify_jwt = false

[functions.generate-report-pdf]
verify_jwt = false

[functions.generate-subscription-document]
verify_jwt = false

[functions.handle-payment-failure]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.pix-webhook]
verify_jwt = false

[functions.process-recurring-payments]
verify_jwt = false

[functions.proposal-follow-up]
verify_jwt = false

[functions.reactivate-customer]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.send-post-service-message]
verify_jwt = false

[functions.send-proposal]
verify_jwt = false

[functions.generate-proposal-pdf]
verify_jwt = false

[functions.send-subscription-document]
verify_jwt = false

[functions.generate-service-document]
verify_jwt = false
